# Generated by Django 4.2.6 on 2024-12-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wadu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Titleinarabic', models.CharField(max_length=5000)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=5000)),
                ('descriptioninarabic', models.CharField(max_length=5000)),
            ],
        ),
    ]
